workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Required rules_python
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.3.0/rules_python-0.3.0.tar.gz",
    sha256 = "934c9ceb552e84577b0faf1e5a2f0450314985b4d8712b2b70717dc679fdc01b",
)

# For this example, we load rules_pyvenv locally. But you'd use http_archive.
local_repository(
    name = "rules_pyvenv",
    path = "../"
)

load("@rules_pyvenv//:repositories.bzl", rules_pyvenv_repositories = "repositories")
rules_pyvenv_repositories()


# Fetch some python packages to install in the venv,
load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
   name = "example_deps",
   requirements = "//:requirements.txt",
)

